# These are supported funding model platforms
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: Borda
# buy_me_a_coffee: # coming soon
custom: ["https://github.com/Borda/Borda/blob/main/SUPPORT.md"]
